/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestOverrideSuperClass */

#ifndef _Included_TestOverrideSubClass
#define _Included_TestOverrideSubClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestOverrideSubClass
 * Method:    func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_TestOverrideSubClass_func
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
