/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test2_Overload */

#ifndef _Included_test2_Overload
#define _Included_test2_Overload
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test2_Overload
 * Method:    my_func
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload_my_1func__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     test2_Overload
 * Method:    my_func
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_test2_Overload_my_1func__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
